### ISSUE TITLE
Multiple cron jobs firing the function multiple times

### ISSUE THREAD

**Issue by wfendler** [PavelVanecek/hubot-cronjob#2]
My goal is to post the message in the code below to a channel once on Tuesday at 3pm and once on Thursday at 3pm. It's getting the day and time right but it's posting the message twice each time. Is there something incorrect about the following code or is this out of the scope of this package?

``` coffeescript
# Description:
#   Defines periodic executions

HubotCron = require 'hubot-cronjob'

module.exports = (robot) ->
  tuesdays = '10 15 * * 3'
  thursdays = '10 15 * * 4'

  timezone = 'America/Chicago'

  fn = ->
    robot.messageRoom 'design-feedback', 'Hey @channel, take a minute and post some work!'

  new HubotCron tuesdays, timezone, fn
  new HubotCron thursdays, timezone, fn
```

**Comment by PavelVanecek** [comment]
I am using similar pattern for posting lunch menus every weekday. The pattern is `0 11 * * 1-5`. It works well.

Judging by your code snippet it looks good and should work.

I think you have several options:
- Try to change your cron pattern to `10 15 * * 3,4` and see if it works
- Try to debug: is it that a Tuesday function is called twice? Or is it because the cron pattern is parsed badly?

This package is using https://github.com/ncb000gt/node-cron behind the curtains so you might find some information there too.
